# Global Configuration for all microservices
namespace: rideshare-prod

# The Loop Array: Helm will iterate over this to build our resources
services:
  price-estimator:
    image: "rideshare/price-estimator:latest"
    port: 8000
    replicas: 2
    isPublic: true
    ingressPath: "/api/v1/estimate"

  payment-api:
    image: "rideshare/payment-api:latest"
    port: 8000
    replicas: 2
    isPublic: false # Strictly internal

  admin-api:
    image: "rideshare/admin-api:latest"
    port: 8000
    replicas: 1
    isPublic: false # Strictly internal

  payment-ui:
    image: "rideshare/payment-ui:latest"
    port: 80
    replicas: 2
    isPublic: true
    ingressPath: "/checkout"

  admin-ui:
    image: "rideshare/admin-ui:latest"
    port: 80
    replicas: 1
    isPublic: true
    ingressPath: "/admin"
